apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nodejs-sample
  labels: 
    app: sample-apps 
spec: 
  replicas: 3 
  selector: 
    matchLabels: 
      app: sample-apps
  template: 
    metadata: 
      labels: 
        app: sample-apps
    spec: 
      containers: 
        - name: sample-apps
          image: zenabar/nodejs:master 
          ports: 
            - containerPort: 3001
