services

apiVersion: v1 
kind: Service 
metadata: 
  name: sample-apps-nodejs
spec: 
  selector: 
    app: sample-apps 
  ports: 
    - protocol: TCP 
      port: 80 
      targetPort: 3000 
  type: LoadBalancer
