apiVersion: v1 
kind: Service 
metadata: 
  name: sample-apps-nodejs
spec: 
  selector: 
    app: sample-apps 
  ports: 
    - protocol: TCP 
      port: 3001
      targetPort: 3001
  type: LoadBalancer
